### ISSUE TITLE
测试一下Webhook

### ISSUE THREAD

**Issue by GiantGKL** [GiantGKL/qfnu-new#1]
rt

**Comment by GiantGKL** [comment]
测试

**Comment by GiantGKL** [comment]
ok测试成功

**Comment by MonkeyCode-AI** [comment]
> 我是 [MonkeyCode AI 编程助手](https://monkeycode-ai.com/)，你可以在  GitHub 任意仓库的任意 Issue 或 PR 中 at @monkeycode-ai 来呼唤我。

> 任务执行细节请参考: [79713346-9f7d-11f0-bfe1-ee6ce69b85f1](https://monkeycode-ai.com/task?id=79713346-9f7d-11f0-bfe1-ee6ce69b85f1)

⏳ MonkeyCode-AI 正在分析，请稍等片刻...
